<a href="https://colab.research.google.com/github/Yurakc/platzi_data/blob/main/Curso%20de%20Fundamentos%20Pr%C3%A1cticos%20de%20Machine%20Learning/5_Comandos_b%C3%A1sicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Comandos básicos de las librerías usadas en el curso (Numpy, Pandas y ScikitLearn)**

# Numpy

Biblioteca de Python comúnmente usada en la ciencias de datos y aprendizaje automático (Machine Learning). Proporciona una estructura de datos de matriz que tiene diversos beneficios sobre las listas regulares.

Importar la biblioteca:

In [ ]:
import numpy as np

Crear arreglo unidimensional:

In [ ]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

Crear arreglo bidimensional:

In [ ]:
np.array( [['x', 'y', 'z'], ['a', 'c', 'e']])

array([['x', 'y', 'z'],
       ['a', 'c', 'e']], dtype='<U1')

Mostrar el número de elementos del arreglo:

In [ ]:
len(my_array)

5

Sumar todos los elementos de un arreglo unidimensional:

In [ ]:
np.sum(my_array)

15

Crear un arreglo de una dimensión con el número 0:

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Crear un arreglo de una dimensión con el número 1:

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Comando de Python para conocer el tipo del dato:

In [ ]:
type(my_array)

numpy.ndarray

Ordenar un arreglo:

In [ ]:
lst = ([3,5,1,4,6])
np.sort(lst )

array([1, 3, 4, 5, 6])

Ordenar un arreglo por su llave:

In [ ]:
cabeceras = [('nombre','S10'),('edad',int)]
datos = [('Juan',10),('Maria',70),('Javier',42),('Samuel',15)]
usuarios = np.array(datos, dtype= cabeceras)

np.sort(usuarios, order='edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

Crear un arreglo de 0 a N elementos:

In [ ]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Crear un arreglo de N a M elementos:

In [ ]:
np.arange(5, 30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

Crear un arreglo de N a M elementos con un espacio de cada X valores:

In [ ]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

Crear arreglo de NxM:

In [ ]:
np.full( (3, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

Número de elementos del arreglo:

In [ ]:
len(my_array)

5

# Pandas

Pandas es una herramienta de manipulación de datos de alto nivel, es construido con la biblioteca de Numpy. Su estructura de datos más importante y clave en la manipulación de la información es DataFrame, el cuál nos va a permitir almacenar y manejar datos tabulados observaciones (filas) y variables (columnas).

Importar la biblioteca:

In [ ]:
import pandas as pd

Generar una serie con Pandas:

In [ ]:
pd.Series([5, 10, 15, 20, 25])

0     5
1    10
2    15
3    20
4    25
dtype: int64

Crear un Dataframe:

In [ ]:
lst = ['Hola', 'mundo', 'robótico']
df = pd.DataFrame(lst)
df

0
0      Hola
1     mundo
2  robótico

Crear un Dataframe con llave y dato:

In [ ]:
data = {'Nombre':['Juan', 'Ana', 'Toño', 'Arturo'],
'Edad':[25, 18, 23, 17],
'Pais': ['MX', 'CO', 'BR', 'MX'] }
df = pd.DataFrame(data)
df

Nombre  Edad Pais
0    Juan    25   MX
1     Ana    18   CO
2    Toño    23   BR
3  Arturo    17   MX

Leer archivo CSV:

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Curso de Fundamentos Prácticos de Machine Learning/Salary_Data.csv')

Mostrar cabecera:

In [ ]:
data.head(3)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0

Mostrar columna del archivo leído:

In [ ]:
data.YearsExperience

0      1.1
1      1.3
2      1.5
3      2.0
4      2.2
5      2.9
6      3.0
7      3.2
8      3.2
9      3.7
10     3.9
11     4.0
12     4.0
13     4.1
14     4.5
15     4.9
16     5.1
17     5.3
18     5.9
19     6.0
20     6.8
21     7.1
22     7.9
23     8.2
24     8.7
25     9.0
26     9.5
27     9.6
28    10.3
29    10.5
Name: YearsExperience, dtype: float64

Mostrar los últimos elementos:

In [ ]:
data.tail()

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

Mostrar tamaño del archivo leído:

In [ ]:
data.shape

(30, 2)

Mostrar columnas:

In [ ]:
data.columns

Index(['YearsExperience', 'Salary'], dtype='object')

Describe una columna:

In [ ]:
data['Salary'].describe()

count        30.000000
mean      76003.000000
std       27414.429785
min       37731.000000
25%       56720.750000
50%       65237.000000
75%      100544.750000
max      122391.000000
Name: Salary, dtype: float64

Ordenar datos del archivo leído:

In [ ]:
data.sort_index(axis=0, ascending=False)

YearsExperience    Salary
29             10.5  121872.0
28             10.3  122391.0
27              9.6  112635.0
26              9.5  116969.0
25              9.0  105582.0
24              8.7  109431.0
23              8.2  113812.0
22              7.9  101302.0
21              7.1   98273.0
20              6.8   91738.0
19              6.0   93940.0
18              5.9   81363.0
17              5.3   83088.0
16              5.1   66029.0
15              4.9   67938.0
14              4.5   61111.0
13              4.1   57081.0
12              4.0   56957.0
11              4.0   55794.0
10              3.9   63218.0
9               3.7   57189.0
8               3.2   64445.0
7               3.2   54445.0
6               3.0   60150.0
5               2.9   56642.0
4               2.2   39891.0
3               2.0   43525.0
2               1.5   37731.0
1               1.3   46205.0
0               1.1   39343.0

# Scikit Learn

Scikit Learn es una biblioteca de Python que está conformada por algoritmos de clasificación, regresión, reducción de la dimensionalidad y clustering. Es una biblioteca clave en la aplicación de algoritmos de Machine Learning, tiene los métodos básicos para llamar un algoritmo, dividir los datos en entrenamiento y prueba, entrenarlo, predecir y ponerlo a prueba.

Importar biblioteca:

In [ ]:
!pip install sklearn

In [ ]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

División del conjunto de datos para entrenamiento y pruebas:

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data[['YearsExperience']],data[['Salary']],test_size=0.25,random_state=0)
X_train, X_test, y_train, y_test

(    YearsExperience
 17              5.3
 22              7.9
 5               2.9
 16              5.1
 8               3.2
 14              4.5
 23              8.2
 20              6.8
 1               1.3
 29             10.5
 6               3.0
 4               2.2
 18              5.9
 19              6.0
 9               3.7
 7               3.2
 25              9.0
 3               2.0
 0               1.1
 21              7.1
 15              4.9
 12              4.0,     YearsExperience
 2               1.5
 28             10.3
 13              4.1
 10              3.9
 26              9.5
 24              8.7
 27              9.6
 11              4.0,       Salary
 17   83088.0
 22  101302.0
 5    56642.0
 16   66029.0
 8    64445.0
 14   61111.0
 23  113812.0
 20   91738.0
 1    46205.0
 29  121872.0
 6    60150.0
 4    39891.0
 18   81363.0
 19   93940.0
 9    57189.0
 7    54445.0
 25  105582.0
 3    43525.0
 0    39343.0
 21   98273.0
 15   67938.0
 12   56957.0,      

Entrenar modelo:

In [ ]:
modelo = DecisionTreeRegressor()
modelo.fit(X_train,y_train)

DecisionTreeRegressor()

Predicción del modelo:

In [ ]:
Y_pred = modelo.predict(X_test)

Matriz de confusión:

In [ ]:
import sklearn.metrics as metrics
metrics.confusion_matrix(y_test,Y_pred)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

Calcular la exactitud:

In [ ]:
metrics.accuracy_score(y_test,Y_pred)

0.0